name: Google Cloud Run Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    name: Google Cloud Run Deploy for Simple-SOE
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_IMAGE_NAME: kineticsquid/${{ secrets.GCP_APPLICATION }}

    steps:

      - uses: actions/checkout@v2

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Gcloud Docker
        run: gcloud auth configure-docker --quiet

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build hub.docker.com Docker image
        run: docker build ./ -t $DOCKER_HUB_IMAGE_NAME

      - name: Push hub.docker.com Docker image
        run: docker push $DOCKER_HUB_IMAGE_NAME

      - name: Google Cloud Deploy Simple SOE by Action
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.GCP_APPLICATION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          source: ./
          region: us-central1
          env_vars: |
            TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}, 
            TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}, 
            REDIS_HOST=${{ secrets.REDIS_HOST }}, 
            REDIS_PORT=${{ secrets.REDIS_PORT }}, 
            REDIS_PW=${{ secrets.REDIS_PW }}, 
            SUDOKU_SOLVER_URL=${{ secrets.SUDOKU_SOLVER_URL }}, 
            JWT_SECRET=${{ secrets.JWT_SECRET }}, 

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"/build